Add Session support
bitrise-steplib/steps-fastlane pull request #43
Opened 2019-03-18 16:37 UTC by BirmacherAkos

2019-03-19 09:44 UTC, trapacska requested changes

2019-03-19 09:44 UTC, trapacska commented on main.go
> +	"github.com/bitrise-io/steps-fastlane/session"
We already have this package in the itunesconnect-deliver step.

2019-03-19 09:44 UTC, trapacska commented on main.go
> +	fs, err := session.GetSession()
Same comments as on the other PRs.

2019-03-19 09:44 UTC, trapacska commented on session/session.go
> +package session
the only(mostly) reason we use packages to use them somewhere else, please do not duplicate the code base, use the pacage from the other PR.

2019-03-19 09:54 UTC, godrei commented on session/session.go
> +package session
import this functionality from the deliver step

2019-03-19 09:54 UTC, godrei requested changes
Pls have a look at my notes

2019-03-22 12:39 UTC, trapacska approved these changes

2019-03-22 13:22 UTC, lszucs approved these changes

2019-03-22 14:41 UTC, merged